[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
chrono = "0.4.38"
log = "0.4.22"
axum = "0.7.5"
tokio = { version = "1.39.2", features = ["full"] }
mongodb = "3.0.1"
shared = { path = "../shared" }
serde_json = "1.0.121"
serde = "1.0.204"
