version: '3.8'

services:
  mongodb:
    image: mongo:5.0.28
    environment:
      - MONGO_INITDB_DATABASE=solforge
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

volumes:
  data: