[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.121"
serde = "1.0.204"
serde_bytes = "0.11.15"
solana-transaction-status = "2.0.3"
solana-sdk = "2.0.3"
chrono = "0.4.38"
