[package]
name = "aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.0.3"
# helius = "0.2.1"
tokio = { version = "1.39.2", features = ["full"] }
tokio-stream = { version = "0.1.15" }
env_logger = "0.11.5"
log = "0.4.22"
futures-core = "0.3.30"
serde_json = "1.0.121"
